export default function DisclaimerPage() {
  return (
    <div className="page-bg">
      <section className="bg-white pt-[90px] pb-20">
        <div className="container-site max-w-3xl">
          <div className="flex items-center gap-3 mb-4">
            <div className="h-[2px] w-8 bg-gold" />
            <span className="text-gold text-[1.4rem] font-bold tracking-[0.12em] uppercase">Legal</span>
          </div>
          <h1 className="section-heading">Disclaimer</h1>
          <div className="flex items-center gap-2 mt-3 mb-2">
            <div className="h-[2px] w-10 bg-gold" />
            <div className="w-2 h-2 rotate-45 border border-gold" />
            <div className="h-[2px] w-10 bg-gold" />
          </div>
          <p className="text-sm text-slate mt-4">Last updated: May 2026</p>

          <div className="mt-10 space-y-8">
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                1. General Disclaimer
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                The information provided on the Pillars of Wisdom platform is for general informational purposes only and does not constitute professional advice of any kind. Nothing on this platform should be interpreted as legal, financial, tax, medical, or regulatory advice, nor should it be relied upon as a substitute for consultation with qualified professionals. Pillars of Wisdom AG makes no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the information, products, services, or related graphics contained on the platform for any purpose. Any reliance you place on such information is therefore strictly at your own risk. You should always consult with appropriately licensed professionals in the relevant field before making any business, legal, financial, or regulatory decisions based on information obtained through the platform.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                2. No Legal, Financial, or Regulatory Advice
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                Pillars of Wisdom AG is a technology company and is not a law firm, financial advisory firm, or compliance consultancy. The platform does not provide legal counsel, financial planning, tax guidance, or regulatory compliance advisory services, and no attorney-client, financial advisor-client, or similar professional relationship is created through your use of the platform. Any outputs, suggestions, or analyses generated by the platform — including those produced by AI-assisted features — are not legal opinions, financial recommendations, or regulatory determinations and should not be treated as such. Users must independently validate all platform outputs with their own qualified legal counsel, financial advisors, and compliance teams before acting on any information provided. The inclusion of regulatory references, compliance frameworks, or industry standards on the platform does not constitute an endorsement, certification, or guarantee of compliance with any specific law, regulation, or industry requirement.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                3. AI-Assisted Outputs
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                The Pillars of Wisdom platform employs artificial intelligence and machine learning models to generate outputs, recommendations, insights, and automated workflows. These outputs are produced algorithmically based on patterns identified in training data and user inputs, and they represent probabilistic estimates rather than certainties. AI models carry inherent limitations, including but not limited to the risk of generating inaccurate, incomplete, or fabricated information — commonly referred to as hallucinations — that may appear plausible despite being factually incorrect. No AI-generated output should be considered a substitute for professional human judgment, and all outputs must be reviewed, validated, and approved by qualified personnel before being relied upon for any business, legal, or regulatory purpose. Pillars of Wisdom AG does not guarantee the accuracy, completeness, timeliness, or fitness for purpose of any AI-generated content. The performance of AI models is influenced by the quality and scope of their training data, which may not encompass all relevant scenarios, jurisdictions, or edge cases applicable to your specific situation.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                4. Accuracy &amp; Completeness
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                While Pillars of Wisdom AG strives to provide accurate and up-to-date information, we make no representation or warranty that the content on the platform is free from errors, omissions, or inaccuracies. Data presented on the platform — including regulatory references, compliance checklists, and industry benchmarks — may contain errors, may not reflect the most current legal or regulatory developments, and may not be applicable to your specific circumstances. The validation and verification of all information remains the sole responsibility of the user. The platform may not always reflect real-time changes in laws, regulations, or industry standards, and there may be delays between when a change occurs and when it is reflected in the platform. Users should independently verify any information obtained from the platform against authoritative sources before relying on it for decision-making.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                5. Regulatory Compliance
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                Regulatory compliance operates under a shared responsibility model between Pillars of Wisdom AG and the customer. While the platform provides tools, workflows, and automation features designed to assist with compliance management, these tools do not replace a customer's own compliance programs, policies, or obligations. Each customer is solely responsible for understanding and meeting its own regulatory requirements, including those specific to its industry, jurisdiction, and business activities. Any certifications, attestations, or compliance designations held by Pillars of Wisdom AG relate to the platform's infrastructure and operations and do not guarantee that customers using the platform will achieve or maintain compliance with any particular regulation or standard. Regulatory requirements vary significantly across jurisdictions, and features or capabilities available on the platform may not satisfy all local, state, federal, or international regulatory obligations applicable to your organization.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                6. Security Disclaimers
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                Pillars of Wisdom AG implements a defense-in-depth security architecture and employs industry-standard measures to protect the platform and its data. However, no system connected to the internet can guarantee absolute security, and we do not represent or warrant that the platform will be immune to all security threats, vulnerabilities, or unauthorized access attempts. The inherent risks of internet-based services mean that data transmission and storage cannot be guaranteed to be completely secure at all times. While we employ multiple layers of security controls — including encryption, access management, monitoring, and regular security assessments — these measures reduce but do not eliminate risk. Users also bear responsibility for maintaining the security of their own access credentials, implementing appropriate access controls within their tenant, and promptly reporting any suspected unauthorized access or security incidents.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                7. Third-Party Services
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                The Pillars of Wisdom platform may integrate with, link to, or reference third-party services, applications, data providers, and APIs to enhance functionality and provide a more comprehensive user experience. These integrations do not constitute an endorsement, recommendation, or certification of any third-party service, and Pillars of Wisdom AG assumes no responsibility for the quality, accuracy, availability, or security of third-party offerings. Your use of any third-party service accessed through or in connection with the platform is governed by that third party's own terms of service, privacy policy, and other agreements, which you should review independently. Pillars of Wisdom AG shall not be liable for any damages, losses, or disruptions arising from third-party service failures, outages, data breaches, or changes to their offerings. Certain platform features may depend on third-party APIs or data sources, and the availability or accuracy of those features may be affected by factors outside our control.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                8. Forward-Looking Statements
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                The platform and its associated materials may contain forward-looking statements regarding future product features, capabilities, roadmaps, performance improvements, and planned enhancements. These statements are based on current expectations, plans, and projections, and are subject to change at any time without notice. Pillars of Wisdom AG undertakes no obligation to update, revise, or deliver any stated features, timelines, or capabilities described in forward-looking statements. Development priorities, resource allocations, and strategic direction may shift based on market conditions, technical feasibility, customer feedback, or other business considerations. Features designated as beta, preview, or early access are provided for evaluation purposes and may be modified, delayed, or discontinued without prior notice. No forward-looking statement should be relied upon as a commitment or guarantee of future performance or availability.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                9. Performance &amp; Results
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                Pillars of Wisdom AG does not guarantee any specific results, outcomes, or performance metrics from the use of the platform. Any efficiency gains, cost savings, time reductions, or other benefits described on the platform are estimates based on typical or representative scenarios and are not promises or guarantees of similar results for any particular user or organization. Past performance, case study outcomes, and benchmark results are not indicative of future results, and individual outcomes will vary based on numerous factors including but not limited to the complexity of your workflows, the quality and volume of your data, your team's expertise, and your organization's specific regulatory environment. Users should conduct their own independent evaluation to determine whether the platform meets their particular needs and expectations.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                10. Jurisdictional Limitations
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                The Pillars of Wisdom platform is controlled and operated from the United States, and its availability, features, and content may not be appropriate or lawful in all jurisdictions. Users accessing the platform from outside the United States do so at their own initiative and are solely responsible for ensuring that their use of the platform complies with all applicable local, state, national, and international laws and regulations. Pillars of Wisdom AG makes no representation that the platform, its content, or its features are available, appropriate, or legal for use in any particular jurisdiction. Certain features, data, or services may be subject to export control laws, trade sanctions, or other governmental restrictions, and users are responsible for ensuring compliance with all such applicable restrictions. If you choose to access the platform from a jurisdiction where its use may be restricted, you assume full responsibility for compliance with local law.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                11. Testimonials &amp; Case Studies
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                Any testimonials, case studies, success stories, or customer endorsements presented on the platform represent the individual experiences and opinions of those customers and are not guarantees that other users will achieve the same or similar results. The results described are representative of specific implementations and should not be interpreted as typical or average outcomes. Individual results may vary significantly based on factors including organizational size, industry, regulatory complexity, data quality, implementation scope, and user adoption. Pillars of Wisdom AG does not claim that the results presented in testimonials or case studies are typical, expected, or guaranteed for any particular customer. No testimonial or case study should be construed as a promise or guarantee of specific performance, savings, or outcomes.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                12. Links &amp; External Content
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                The platform may contain links to external websites, resources, documents, or third-party content that are provided for convenience and informational purposes only. The inclusion of any link does not imply endorsement, recommendation, or approval by Pillars of Wisdom AG of the linked website, its content, its operator, or any products or services offered therein. We have no control over the nature, content, accuracy, or availability of external sites, and we assume no responsibility for any damage, loss, or offense caused by or in connection with the use of any such external content. Linking to any external site does not constitute a recommendation to use or patronize that site, and users should review the terms, privacy policies, and content of any external site independently. Pillars of Wisdom AG reserves the right to remove or modify any links at any time without notice.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                13. Contact
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                If you have questions about this Disclaimer or need further clarification regarding any of the sections above, please contact us at:{" "}
                <a
                  href="mailto:hello@pillarsofwisdom.ai"
                  className="text-gold hover:underline"
                >
                  hello@pillarsofwisdom.ai
                </a>
              </p>
            </section>
          </div>
        </div>
      </section>
    </div>
  )
}