export default function TermsPage() {
  return (
    <div className="page-bg">
      <section className="bg-white pt-[90px] pb-20">
        <div className="container-site max-w-3xl">
          <div className="flex items-center gap-3 mb-4">
            <div className="h-[2px] w-8 bg-gold" />
            <span className="text-gold text-[1.4rem] font-bold tracking-[0.12em] uppercase">Legal</span>
          </div>
          <h1 className="section-heading">Terms of Service</h1>
          <div className="flex items-center gap-2 mt-3 mb-2">
            <div className="h-[2px] w-10 bg-gold" />
            <div className="w-2 h-2 rotate-45 border border-gold" />
            <div className="h-[2px] w-10 bg-gold" />
          </div>
          <p className="text-sm text-slate mt-4">Last updated: May 2026</p>

          <div className="mt-10 space-y-8">
            {/* 1. Acceptance of Terms */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                1. Acceptance of Terms
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                By accessing or using the Pillars of Wisdom platform ("Platform"), you acknowledge that you have read, understood, and agree to be bound by these Terms of Service ("Terms") and all applicable policies referenced herein, including our Privacy Policy and Acceptable Use Policy. These Terms constitute a legally binding agreement between you ("Customer") and Pillars of Wisdom AG ("Company," "we," "us," or "our"). If you are entering into these Terms on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                We reserve the right to modify these Terms at any time by posting the revised version on the Platform or by notifying you via email. Material changes will be communicated with at least thirty (30) days' prior notice. Your continued use of the Platform following the effective date of any modification constitutes your acceptance of the revised Terms. If you do not agree to the modified Terms, you must discontinue use of the Platform and, if applicable, terminate your subscription in accordance with the termination provisions set forth herein.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                If any provision of these Terms is held to be unenforceable or invalid by a court of competent jurisdiction, such provision shall be modified to the minimum extent necessary to make it valid and enforceable, and the remaining provisions shall remain in full force and effect. The failure of either party to enforce any right or provision of these Terms shall not constitute a waiver of such right or provision.
              </p>
            </section>

            {/* 2. Definitions */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                2. Definitions
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                <strong>"Platform"</strong> means the Pillars of Wisdom multi-tenant enterprise operational platform, including all software, modules, APIs, dashboards, and related services provided by the Company. <strong>"Services"</strong> means all services provided by the Company to the Customer under these Terms and any applicable Order Form, including implementation, training, support, and consulting services. <strong>"Customer"</strong> means the organization that has entered into an Order Form with the Company for access to the Platform and Services.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                <strong>"User"</strong> means any individual authorized by the Customer to access the Platform through a user account, including employees, contractors, and agents of the Customer. <strong>"Tenant Data"</strong> means all data, documents, records, files, and information that the Customer or its Users upload, input, or generate through the Platform. <strong>"AI Outputs"</strong> means any content, recommendations, analyses, summaries, or other outputs generated by the Platform's artificial intelligence capabilities in response to Tenant Data or User inputs.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                <strong>"Documentation"</strong> means the user guides, technical specifications, API references, and other materials provided by the Company to assist the Customer in using the Platform. <strong>"Order Form"</strong> means the ordering document, statement of work, or subscription agreement executed by the parties that specifies the Services, subscription term, fees, and other commercial terms. <strong>"SOW"</strong> means a Statement of Work that describes specific professional services, deliverables, timelines, and fees agreed upon by the parties.
              </p>
            </section>

            {/* 3. Platform Description */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                3. Platform Description
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                Pillars of Wisdom is a sovereign AI operating system delivered as a multi-tenant enterprise platform purpose-built for regulated industries, including mortgage, banking, legal, healthcare, government, insurance, real estate, and accounting. The Platform provides a unified environment for workflow automation, document management, AI-assisted decisioning, compliance monitoring, and governance tooling designed to meet the stringent requirements of highly regulated operational environments.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                The Platform comprises modular capabilities that may be provisioned based on the Customer's subscription, including but not limited to: intelligent document processing, regulatory compliance engines, audit trail and governance tooling, role-based access management, AI-powered analysis and recommendation systems, and integration frameworks for connecting with third-party systems. Each module operates within the Platform's unified security and governance framework, ensuring consistent policy enforcement and data protection across all capabilities.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                The Platform's AI capabilities leverage large language models and machine learning systems to assist Users with document review, data extraction, risk assessment, and decision support. These AI capabilities are designed to augment human judgment and are subject to the disclaimers and limitations set forth in Section 8. The Company reserves the right to update, modify, or discontinue any Platform feature or module with reasonable notice, except where such changes are addressed in an applicable Order Form.
              </p>
            </section>

            {/* 4. Account & Access */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                4. Account & Access
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                Access to the Platform requires a valid user account registered by or on behalf of an authorized Customer. The Customer is responsible for all activities conducted under its tenant account and for ensuring that each User maintains the confidentiality of their login credentials. The Customer must notify the Company immediately upon discovering any unauthorized access or use of its account. The Company shall not be liable for any loss or damage arising from the Customer's failure to safeguard its credentials.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                Each User must be assigned an individual account and may not share credentials with any other person. The Customer is responsible for managing User access levels, including the assignment and revocation of permissions, through the Platform's administrative tools. The Company may require multi-factor authentication (MFA) or additional security measures for certain access levels or in response to security events. The Customer agrees to implement and enforce such measures as a condition of continued access.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                The Company reserves the right to suspend or terminate access for any User or Customer account that violates these Terms, exhibits suspicious activity, or poses a security risk to the Platform. In the event of a suspension, the Company will make commercially reasonable efforts to notify the Customer and provide an opportunity to remediate the issue, except where immediate suspension is necessary to prevent harm. The Customer is responsible for all fees incurred during the subscription term regardless of any suspension.
              </p>
            </section>

            {/* 5. Acceptable Use */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                5. Acceptable Use
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                The Customer and its Users shall use the Platform only for lawful business purposes and in compliance with all applicable federal, state, and local laws, regulations, and industry standards. The Customer shall not use the Platform in any manner that could damage, disable, overburden, or impair the Platform's infrastructure or interfere with any other party's use and enjoyment of the Platform.
              </p>
              <h3 className="font-heading text-base font-semibold text-navy mb-1 mt-4">
                5.1 Prohibited Uses
              </h3>
              <p className="text-sm text-slate leading-relaxed">
                The following uses are strictly prohibited: (a) reverse engineering, decompiling, disassembling, or otherwise attempting to derive the source code of the Platform; (b) accessing or attempting to access any part of the Platform or related systems beyond the scope of authorized access; (c) using the Platform to process, store, or transmit content that is unlawful, defamatory, harassing, or otherwise objectionable; (d) introducing malicious code, viruses, or any technology that could harm the Platform or its Users; (e) using automated means to scrape, extract, or collect data from the Platform without authorization; (f) reselling, sublicensing, or redistributing access to the Platform without prior written consent.
              </p>
              <h3 className="font-heading text-base font-semibold text-navy mb-1 mt-4">
                5.2 Regulatory Compliance
              </h3>
              <p className="text-sm text-slate leading-relaxed">
                Customers operating in regulated industries are solely responsible for ensuring their use of the Platform complies with all applicable regulatory requirements, including but not limited to those imposed by the Consumer Financial Protection Bureau (CFPB), Office of the Comptroller of the Currency (OCC), Federal Deposit Insurance Corporation (FDIC), Department of Housing and Urban Development (HUD), Health Insurance Portability and Accountability Act (HIPAA), and state bar associations. The Company provides compliance-oriented tooling but does not guarantee that any Customer's use of the Platform will satisfy any specific regulatory obligation.
              </p>
            </section>

            {/* 6. Subscription & Licensing */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                6. Subscription & Licensing
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                Subject to the Customer's payment of applicable fees and compliance with these Terms, the Company grants the Customer a non-exclusive, non-transferable, limited license to access and use the Platform and Services for the subscription term specified in the applicable Order Form. This license is limited to the number of authorized User seats, modules, and usage tiers set forth in the Order Form. Any use beyond the licensed scope requires additional authorization and may incur additional fees.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                The Customer may not: (a) copy, modify, or create derivative works of the Platform; (b) rent, lease, lend, sell, sublicense, or otherwise distribute the Platform to third parties; (c) use the Platform to provide competitive benchmarking or to build a competing product or service; (d) remove, alter, or obscure any proprietary notices on the Platform; or (e) use the Platform in a manner that exceeds the usage limits or scope defined in the Order Form. Seat-based licensing is measured per unique User account, and concurrent or shared accounts are not permitted unless expressly authorized in the Order Form.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                Module access is governed by the Customer's subscription tier. Access to specific modules, features, or capabilities may be added or removed during the subscription term through a change order or amendment to the Order Form. The Company reserves the right to reorganize or rename modules, provided that the Customer's contracted functionality is not materially diminished during the then-current subscription term.
              </p>
            </section>

            {/* 7. Data Ownership & Privacy */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                7. Data Ownership & Privacy
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                The Customer retains all right, title, and interest in and to Tenant Data. The Company does not claim any ownership rights in Tenant Data. The Company shall not access, use, or disclose Tenant Data except as necessary to provide the Services, as required by law, or as expressly authorized by the Customer. The Company will not use Tenant Data to train, improve, or develop its AI models or any other product or service without the Customer's explicit written consent.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                The Company processes Tenant Data in accordance with its Privacy Policy, which is incorporated herein by reference. The Customer acknowledges that the Company may process Tenant Data using subprocessors as described in the Privacy Policy and any applicable Data Processing Addendum. The Company maintains a list of authorized subprocessors and will provide notice of material changes to such list. The Customer may object to a new subprocessor in accordance with the procedures set forth in the Data Processing Addendum.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                The Platform employs logical and physical isolation to ensure that each Customer's Tenant Data is segregated from the data of all other tenants. The Company implements encryption in transit and at rest, role-based access controls, and continuous monitoring to protect Tenant Data. The Customer is responsible for configuring its own data sharing and access policies within the Platform. Data sovereignty requirements, including data residency and localization obligations, are addressed in the applicable Order Form or Data Processing Addendum.
              </p>
            </section>

            {/* 8. AI-Assisted Outputs */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                8. AI-Assisted Outputs
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                The Platform utilizes artificial intelligence and machine learning systems to generate AI Outputs, including but not limited to document summaries, risk assessments, compliance recommendations, data extractions, and analytical insights. AI Outputs are generated algorithmically based on patterns identified in data and are inherently probabilistic in nature. The Company makes no representation or warranty that any AI Output is accurate, complete, current, or suitable for any particular purpose.
              </p>
              <h3 className="font-heading text-base font-semibold text-navy mb-1 mt-4">
                8.1 Not Legal, Financial, or Professional Advice
              </h3>
              <p className="text-sm text-slate leading-relaxed">
                AI Outputs do not constitute legal advice, financial advice, tax advice, medical advice, or any other form of professional counsel. The Platform is a tool designed to assist qualified professionals in their decision-making processes, not to replace human judgment. Customers operating in regulated industries must ensure that all AI Outputs are reviewed by appropriately licensed and qualified professionals before being relied upon for any business, legal, or regulatory purpose.
              </p>
              <h3 className="font-heading text-base font-semibold text-navy mb-1 mt-4">
                8.2 Human Review Required
              </h3>
              <p className="text-sm text-slate leading-relaxed">
                The Customer is solely responsible for reviewing, verifying, and validating all AI Outputs before acting upon them, distributing them to third parties, or incorporating them into any official record, filing, or decision. The Company strongly recommends that all AI Outputs undergo human expert review as part of the Customer's standard operating procedures. The Customer acknowledges that reliance on AI Outputs without adequate human review may result in errors, omissions, or regulatory non-compliance for which the Company bears no responsibility.
              </p>
              <h3 className="font-heading text-base font-semibold text-navy mb-1 mt-4">
                8.3 Training Data & Model Limitations
              </h3>
              <p className="text-sm text-slate leading-relaxed">
                The AI models used by the Platform are trained on diverse datasets that may include publicly available information, licensed data, and anonymized, aggregated patterns. The Company does not use Customer Tenant Data to train its models unless explicitly authorized. AI models have inherent limitations, including potential biases, hallucinations, and knowledge cutoffs. The Company does not guarantee that AI Outputs will be free from errors, biases, or inconsistencies, and the Customer assumes all risk associated with the use of AI Outputs.
              </p>
            </section>

            {/* 9. Intellectual Property */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                9. Intellectual Property
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                The Platform, including all software, source code, object code, user interfaces, designs, algorithms, models, documentation, and any modifications or derivative works thereof, is the exclusive intellectual property of the Company and is protected by copyright, trademark, patent, trade secret, and other intellectual property laws. No title to or ownership of the Platform or any component thereof is transferred to the Customer under these Terms.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                The Customer retains all right, title, and interest in and to Tenant Data, including any intellectual property rights therein. The Company acknowledges that Tenant Data is and shall remain the property of the Customer. The Customer grants the Company a limited, non-exclusive license to process Tenant Data solely for the purpose of providing the Services during the subscription term.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                If the Customer provides the Company with any feedback, suggestions, or ideas regarding the Platform ("Feedback"), the Customer hereby grants the Company a non-exclusive, royalty-free, perpetual, irrevocable license to use, implement, and incorporate such Feedback into the Platform without any obligation of attribution or compensation. The Company's trademarks, service marks, and logos may not be used by the Customer without prior written consent. The Platform may include or incorporate open source software components, which are subject to the terms of their respective licenses, as identified in the Documentation.
              </p>
            </section>

            {/* 10. Service Availability & SLAs */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                10. Service Availability & SLAs
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                The Company will use commercially reasonable efforts to make the Platform available twenty-four hours a day, seven days a week, excluding scheduled maintenance windows and force majeure events. The Company targets a monthly uptime percentage of 99.9% for the Platform, measured as the total minutes in a month minus the aggregate minutes of unplanned downtime, divided by the total minutes in the month. Uptime calculations exclude downtime resulting from Customer-caused issues, scheduled maintenance, or force majeure events.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                The Company will provide at least seventy-two (72) hours' advance notice of scheduled maintenance windows, which will be scheduled during low-usage periods whenever practicable. Emergency maintenance may be performed without advance notice where necessary to address critical security vulnerabilities or service-impacting defects. The Company will use commercially reasonable efforts to minimize the duration and impact of all maintenance activities.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                If the Platform fails to meet the applicable uptime commitment in any calendar month, the Customer may request service credits as set forth in the applicable Order Form or Service Level Agreement. Service credits are the Customer's sole and exclusive remedy for any failure to meet the uptime commitment. Force majeure events, including but not limited to natural disasters, acts of terrorism, war, pandemics, government actions, internet outages, and power failures, shall not constitute a breach of these Terms or any uptime commitment.
              </p>
            </section>

            {/* 11. Compliance & Regulatory */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                11. Compliance & Regulatory
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                Compliance with applicable laws, regulations, and industry standards is a shared responsibility between the Company and the Customer. The Company is responsible for maintaining the security, availability, and confidentiality of the Platform infrastructure in accordance with its SOC 2 Type II certification and any other compliance commitments specified in the applicable Order Form. The Company maintains administrative, technical, and physical safeguards designed to protect Tenant Data and support the Customer's compliance objectives.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                The Customer is responsible for its own use of the Platform, including ensuring that its use complies with all applicable regulatory requirements specific to its industry and jurisdiction. The Company's compliance certifications (including SOC 2, HIPAA, and PCI DSS where applicable) address the Company's obligations as a service provider and do not extend to the Customer's use of the Platform. The Customer must implement its own policies, procedures, and controls to satisfy its regulatory obligations, including those related to data handling, record retention, and consumer protection.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                Upon reasonable written request and subject to confidentiality obligations, the Company will provide the Customer with access to audit reports, compliance certifications, and other documentation reasonably necessary to verify the Company's compliance with its obligations under these Terms. The Customer may conduct an audit of the Company's security practices no more than once per year, provided that such audit is conducted during normal business hours and does not unreasonably interfere with the Company's operations. The Customer shall bear all costs associated with any such audit.
              </p>
            </section>

            {/* 12. Confidentiality */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                12. Confidentiality
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                Each party ("Receiving Party") agrees to hold in confidence all non-public information disclosed by the other party ("Disclosing Party") that is designated as confidential or that reasonably should be understood to be confidential given the nature of the information and the circumstances of disclosure ("Confidential Information"). The Receiving Party shall not disclose Confidential Information to any third party except as necessary to perform its obligations under these Terms, and shall use the same degree of care it uses to protect its own confidential information, but in no event less than reasonable care.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                Confidential Information does not include information that: (a) is or becomes publicly available without breach of these Terms; (b) was known to the Receiving Party prior to disclosure; (c) is independently developed by the Receiving Party without reference to the Disclosing Party's Confidential Information; or (d) is rightfully received from a third party without restriction. The Receiving Party may disclose Confidential Information to the extent required by law or court order, provided that the Receiving Party gives the Disclosing Party prompt written notice and reasonable assistance in seeking a protective order.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                Upon termination of these Terms or upon the Disclosing Party's written request, the Receiving Party shall promptly return or destroy all copies of Confidential Information in its possession and certify in writing that it has done so. These confidentiality obligations shall survive termination of these Terms for a period of three (3) years, except with respect to trade secrets, which shall remain protected for as long as such information qualifies as a trade secret under applicable law.
              </p>
            </section>

            {/* 13. Indemnification */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                13. Indemnification
              </h2>
              <h3 className="font-heading text-base font-semibold text-navy mb-1 mt-4">
                13.1 Customer Indemnification
              </h3>
              <p className="text-sm text-slate leading-relaxed">
                The Customer agrees to indemnify, defend, and hold harmless the Company and its officers, directors, employees, and agents from and against any and all claims, damages, losses, and expenses (including reasonable attorneys' fees) arising from or related to: (a) the Customer's breach of these Terms; (b) the Customer's use of the Platform in violation of applicable laws or regulations; (c) any claim that Tenant Data or Customer-provided content infringes the intellectual property rights of a third party; and (d) any claim arising from the Customer's reliance on AI Outputs without adequate human review.
              </p>
              <h3 className="font-heading text-base font-semibold text-navy mb-1 mt-4">
                13.2 Company Indemnification
              </h3>
              <p className="text-sm text-slate leading-relaxed">
                The Company agrees to indemnify, defend, and hold harmless the Customer from and against any and all claims, damages, losses, and expenses (including reasonable attorneys' fees) arising from or related to any claim that the Platform, as provided and used in accordance with these Terms, infringes the intellectual property rights of a third party. If the Platform becomes or in the Company's reasonable opinion is likely to become the subject of an infringement claim, the Company may, at its option: (a) modify the Platform to make it non-infringing; (b) obtain a license for the Customer's continued use; or (c) terminate the affected subscription with a pro rata refund of prepaid fees.
              </p>
              <h3 className="font-heading text-base font-semibold text-navy mb-1 mt-4">
                13.3 Indemnification Process
              </h3>
              <p className="text-sm text-slate leading-relaxed">
                The indemnifying party's obligations are conditioned upon the indemnified party: (a) providing prompt written notice of the claim; (b) granting the indemnifying party sole control of the defense and settlement of the claim; and (c) providing reasonable cooperation at the indemnifying party's expense. The indemnified party may participate in the defense at its own expense with counsel of its choice. No settlement that imposes any admission of liability or obligation on the indemnified party may be entered into without the indemnified party's prior written consent.
              </p>
            </section>

            {/* 14. Limitation of Liability */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                14. Limitation of Liability
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                To the maximum extent permitted by applicable law, neither party shall be liable to the other for any indirect, incidental, special, consequential, punitive, or exemplary damages, including but not limited to damages for loss of profits, revenue, data, goodwill, or business opportunities, arising out of or related to these Terms or the use of the Platform, regardless of the cause of action or the theory of liability, even if such party has been advised of the possibility of such damages.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                The total aggregate liability of either party under these Terms shall not exceed the total fees paid or payable by the Customer to the Company during the twelve (12) month period immediately preceding the event giving rise to the claim. This limitation applies regardless of the cause of action or the theory of liability, whether in contract, tort (including negligence), strict liability, or any other legal theory.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                The foregoing limitations of liability shall not apply to: (a) either party's obligations under Section 12 (Confidentiality); (b) the Customer's indemnification obligations under Section 13; (c) the Company's indemnification obligations under Section 13; (d) claims for unauthorized access to or misuse of Tenant Data; or (e) either party's breach of its intellectual property obligations. These exclusions reflect the allocation of risk between the parties and are an essential basis of the bargain.
              </p>
            </section>

            {/* 15. Term & Termination */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                15. Term & Termination
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                These Terms become effective upon the Customer's acceptance and remain in effect for the subscription term specified in the applicable Order Form ("Initial Term"). Upon expiration of the Initial Term, the subscription will automatically renew for successive twelve (12) month periods ("Renewal Terms") unless either party provides written notice of non-renewal at least thirty (30) days prior to the expiration of the then-current term. Fees for Renewal Terms are subject to adjustment with sixty (60) days' prior notice.
              </p>
              <h3 className="font-heading text-base font-semibold text-navy mb-1 mt-4">
                15.1 Termination for Cause
              </h3>
              <p className="text-sm text-slate leading-relaxed">
                Either party may terminate these Terms upon written notice if the other party materially breaches these Terms and fails to cure such breach within thirty (30) days of receiving written notice specifying the breach. The Company may terminate immediately upon notice if the Customer: (a) fails to pay any undisputed fees when due; (b) violates the Acceptable Use provisions; (c) becomes subject to bankruptcy or insolvency proceedings; or (d) engages in conduct that poses a security risk to the Platform or other Customers.
              </p>
              <h3 className="font-heading text-base font-semibold text-navy mb-1 mt-4">
                15.2 Termination for Convenience
              </h3>
              <p className="text-sm text-slate leading-relaxed">
                The Customer may terminate these Terms for convenience upon sixty (60) days' written notice, subject to payment of all fees due through the end of the then-current term. Early termination fees, if any, are specified in the applicable Order Form. The Company may terminate these Terms for convenience upon ninety (90) days' written notice, in which case the Company will provide a pro rata refund of any prepaid fees for the unused portion of the subscription term.
              </p>
              <h3 className="font-heading text-base font-semibold text-navy mb-1 mt-4">
                15.3 Effect of Termination
              </h3>
              <p className="text-sm text-slate leading-relaxed">
                Upon termination or expiration, the Customer's right to access and use the Platform will immediately cease. The Company will make Tenant Data available for export in a commonly used electronic format for a period of thirty (30) days following termination ("Retrieval Period"). After the Retrieval Period, the Company will delete or anonymize all Tenant Data in accordance with its data retention policies, unless retention is required by applicable law. The Company will provide reasonable transition assistance during the Retrieval Period to facilitate the Customer's migration of Tenant Data to an alternative system.
              </p>
            </section>

            {/* 16. Dispute Resolution */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                16. Dispute Resolution
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                The parties agree to attempt to resolve any dispute arising out of or related to these Terms through good faith negotiation. Either party may initiate the negotiation process by providing written notice of the dispute to the other party. The parties' respective senior management will meet within fifteen (15) business days of such notice to attempt to resolve the dispute. If the dispute is not resolved within thirty (30) days of the initial notice, either party may proceed to mediation as set forth below.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                If negotiation is unsuccessful, the parties agree to submit the dispute to non-binding mediation administered by a mutually agreed-upon mediator. The parties will share the costs of mediation equally. If mediation fails to resolve the dispute within sixty (60) days, either party may submit the dispute to binding arbitration administered by the American Arbitration Association (AAA) under its Commercial Arbitration Rules. The arbitration shall be conducted in Palm Beach County, Florida, by a single arbitrator with experience in technology disputes. The arbitrator's decision shall be final and binding, and judgment upon the award may be entered in any court of competent jurisdiction.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                These Terms shall be governed by and construed in accordance with the laws of the State of Florida, without regard to its conflict of law provisions. The parties expressly waive any right to a jury trial in connection with any dispute arising under these Terms. The Customer agrees that any dispute resolved through arbitration shall not be brought as a class action, collective action, or representative action, and the arbitrator shall have no authority to consolidate or join the claims of multiple parties or to award relief on a class-wide, collective, or representative basis.
              </p>
            </section>

            {/* 17. Miscellaneous */}
            <section>
              <h2 className="font-heading text-xl font-semibold text-navy mb-2">
                17. Miscellaneous
              </h2>
              <p className="text-sm text-slate leading-relaxed">
                These Terms, together with any applicable Order Forms, SOWs, and policies referenced herein, constitute the entire agreement between the parties with respect to the subject matter hereof and supersede all prior or contemporaneous agreements, understandings, negotiations, and discussions, whether oral or written. In the event of a conflict between these Terms and an Order Form, the Order Form shall prevail with respect to its specific subject matter.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                The Company may amend these Terms as set forth in Section 1. No waiver of any provision of these Terms shall be effective unless made in writing and signed by the waiving party. The failure of either party to enforce any right or provision shall not constitute a waiver of such right or provision. The Customer may not assign or transfer its rights or obligations under these Terms without the prior written consent of the Company, and any purported assignment without such consent shall be void. The Company may assign these Terms to an affiliate or in connection with a merger, acquisition, or sale of all or substantially all of its assets.
              </p>
              <p className="text-sm text-slate leading-relaxed mt-3">
                If any provision of these Terms is held to be invalid or unenforceable by a court of competent jurisdiction, such provision shall be modified to the minimum extent necessary to make it valid and enforceable, and the remaining provisions shall continue in full force and effect. All notices required or permitted under these Terms shall be in writing and delivered by email to the address provided by the parties, or to such other address as either party may designate in writing. For all legal notices to the Company, please contact:{" "}
                <a
                  href="mailto:hello@pillarsofwisdom.ai"
                  className="text-gold hover:underline"
                >
                  hello@pillarsofwisdom.ai
                </a>
                . Pillars of Wisdom AG is headquartered in the State of Florida, United States.
              </p>
            </section>
          </div>
        </div>
      </section>
    </div>
  )
}